aliases:
  # Cache Management
  - &restore-cabal-cache
    keys:
      - 1-cabal-{{ arch }}-{{ checksum "zei-li.cabal" }}
  - &save-cabal-cache
    paths:
      - /root/.cabal
    key: 1-cabal-{{ arch }}-{{ checksum "zei-li.cabal" }}
 
  - &update-package-list
    name: update-package-list
    command: |
      if [ ! -d /root/.cabal ]; then
        echo "updating cabal package-list ..."
        cabal update
      fi

version: 2
jobs:
  lint:
    docker:
      - image: yufrice/yesod-hlint
    
    working_directory: /project

    steps:
      - checkout
      - run: hlint src 
  build:
    docker:
      - image: haskell

    working_directory: /project

    steps:
      - checkout
      - restore-cache: *restore-cabal-cache
      - run: *update-package-list
      - run: cabal new-build
      - save_cache: *save-cabal-cache
workflows:
  version: 2
  lint_build:
    jobs:
      - lint:
          filters:
            branches:
              only:
                - /^feature\/.*/
                - /^hotfix\/.*/
                - develop
      - build:
          requires:
            - lint
          filters:
            branches:
              only:
                - /^feature\/.*/
                - /^hotfix\/.*/
                - develop
