aliases:
  # Cache Management
  - &restore-cabal-build-cache
    keys:
      - 1-cabal-build-{{ arch }}-{{ checksum "zei-li.cabal" }}
  - &save-cabal-build-cache
    paths:
      - /root/.cabal
    key: 1-cabal-build-{{ arch }}-{{ checksum "zei-li.cabal" }}
  - &restore-cabal-test-cache
    keys:
      - 1-cabal-test-{{ arch }}-{{ checksum "zei-li.cabal" }}
  - &save-cabal-test-cache
    paths:
      - /root/.cabal
    key: 1-cabal-test-{{ arch }}-{{ checksum "zei-li.cabal" }}
 
  - &update-package-list
    name: update-package-list
    command: |
      if [ ! -d /root/.cabal ]; then
        echo "updating cabal package-list ..."
        cabal update
      fi

version: 2
jobs:
  lint:
    docker:
      - image: yufrice/yesod-hlint
    
    working_directory: /project

    steps:
      - checkout
      - run: hlint src 
  build:
    docker:
      - image: haskell

    working_directory: /project

    steps:
      - checkout
      - restore-cache: *restore-cabal-build-cache
      - run: *update-package-list
      - run: cabal new-build
      - save_cache: *save-cabal-build-cache
  test:
    docker:
      - image: haskell

    working_directory: /project

    steps:
      - checkout
      - restore-cache: *restore-cabal-test-cache
      - run: *update-package-list
      - run: cabal new-test unit-tests
      - save_cache: *save-cabal-test-cache
  integ-test:
    docker:
      - image: haskell

    working_directory: /project

    steps:
      - checkout
      - restore-cache: *restore-cabal-test-cache
      - run: *update-package-list
      - run: cabal new-test integ-tests
      - save_cache: *save-cabal-test-cache
workflows:
  version: 2
  lint_build_test:
    jobs:
      - lint:
          filters:
            branches:
              only:
                - /^feature\/.*/
                - /^hotfix\/.*/
                - develop
      - build:
          requires:
            - lint
          filters:
            branches:
              only:
                - /^feature\/.*/
                - /^hotfix\/.*/
                - develop
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - /^feature\/.*/
                - /^hotfix\/.*/
                - develop
      - integ-test:
          requires:
            - test
          filters:
            branches:
              only:
                - /^feature\/.*/
                - /^hotfix\/.*/
                - develop
